### ISSUE TITLE
Creación del footer de la página principal

### ISSUE THREAD

**Issue by israteneda** [AcademiaTemple/website#10]
![image](https://user-images.githubusercontent.com/20668624/96077267-ef606800-0e74-11eb-968d-19814991b7cc.png)

Crear la sección que se muestra en la imagen

Para ver el diseño completo se pueden dirigir [al prototipo en Figma](https://www.figma.com/file/KnjnTglY03uWmKg3gFhQMM/Academia_Temple?node-id=0%3A1)

Si tienes dudas, o sugerencias se pueden comunicar en el canal de [Discord](https://discord.gg/34M35T7)

**Comment by fvalverdeu** [comment]
Hola!! Por favor asignarme el footer...

**Comment by israteneda** [comment]
El issue se ha cerrado con el pull #26
