### ISSUE TITLE
Creación de las tarjetas "Nuestro alumnos y docentes"

### ISSUE THREAD

**Issue by Gricardov** [AcademiaTemple/website#11]
![image](https://user-images.githubusercontent.com/20552678/96077374-3d756b80-0e75-11eb-8e35-cb5de58dc5a5.png)

Incluyendo el título 

Para ver el diseño completo se pueden dirigir [al prototipo en Figma](https://www.figma.com/file/KnjnTglY03uWmKg3gFhQMM/Academia_Temple?node-id=0%3A1)

Si tienes dudas, o sugerencias se pueden comunicar en el canal de [Discord](https://discord.gg/34M35T7)

**Comment by williams23cc** [comment]
Hola, estaré trabajando en este issue.

**Comment by edavot** [comment]
Comienzo con este issue

**Comment by israteneda** [comment]
Ok
