### ISSUE TITLE
Creación del carrusel de la página docentes

### ISSUE THREAD

**Issue by israteneda** [AcademiaTemple/website#12]
![image](https://user-images.githubusercontent.com/20668624/96077741-38fd8280-0e76-11eb-95df-154af89de049.png)

Crear la sección que se muestra en la imagen

Para ver el diseño completo se pueden dirigir [al prototipo en Figma](https://www.figma.com/file/KnjnTglY03uWmKg3gFhQMM/Academia_Temple?node-id=0%3A1)

Si tienes dudas, o sugerencias se pueden comunicar en el canal de [Discord](https://discord.gg/34M35T7)

**Comment by anarquia17** [comment]
Este issue lo estaré trabajando.

**Comment by anarquia17** [comment]
Estimados comunicó que para el carrusel se instalará al modulo los estilos de bootstrap.

**Comment by israteneda** [comment]
Talvez podrías buscar algún carrusel sin bootstrap más que todo para no afectar a los otros issues en caso que alguien esté trabajando en los otros issues con css puro

**Comment by GerardoQ-prog** [comment]
Habiamos quedado con css puro :) 
pero por mi bien si es que se usa bootstrap, por favor avisar en caso se pueda usar para el tema del responsive

**Comment by anarquia17** [comment]
Si agrege el bootstrap para que sea responsivo. Sobre la marcha vamos apoyandonos para que no tengan ningun problema con boostrap.

**Comment by israteneda** [comment]
Resuelto por @anarquia17 en #27
