### ISSUE TITLE
Crear tarjeta de docente en la página docentes

### ISSUE THREAD

**Issue by israteneda** [AcademiaTemple/website#13]
![image](https://user-images.githubusercontent.com/20668624/96078336-9e9e3e80-0e77-11eb-8c8f-58110cbbc60b.png)

Crear la sección que se muestra en la imagen

Para ver el diseño completo se pueden dirigir [al prototipo en Figma](https://www.figma.com/file/KnjnTglY03uWmKg3gFhQMM/Academia_Temple?node-id=0%3A1)

Si tienes dudas, o sugerencias se pueden comunicar en el canal de [Discord](https://discord.gg/34M35T7)

**Comment by anarquia17** [comment]
Trabajere en este issue.
