### ISSUE TITLE
Unir página de docentes

### ISSUE THREAD

**Issue by Gricardov** [AcademiaTemple/website#14]
![image](https://user-images.githubusercontent.com/20552678/96078381-bc6ba380-0e77-11eb-8b3f-30a6cac03313.png)
Unir Header, Tarjeta superior, párrafos, tarjetas de cursos y footer.

Requisitos:
Tener Header
Tarjeta perfil
Párrados
Tarjetas de cursos
Footer

**Comment by israteneda** [comment]
Resuelto por @Grover101 en #38
