### ISSUE TITLE
Tarjeta de cursos de la página detalle de docente

### ISSUE THREAD

**Issue by israteneda** [AcademiaTemple/website#15]
![image](https://user-images.githubusercontent.com/20668624/96078677-a5798100-0e78-11eb-99ae-565a37e7abd4.png)

Crear la sección que se muestra en la imagen

Para ver el diseño completo se pueden dirigir [al prototipo en Figma](https://www.figma.com/file/KnjnTglY03uWmKg3gFhQMM/Academia_Temple?node-id=0%3A1)

Si tienes dudas, o sugerencias se pueden comunicar en el canal de [Discord](https://discord.gg/34M35T7)

**Comment by rokkoo** [comment]
podría hacer esta issue?

**Comment by israteneda** [comment]
Claro @rokkoo

**Comment by israteneda** [comment]
Resulto por @Grover101 en #37
