### ISSUE TITLE
Consulta para trabajar el proyecto con bootstrap 

### ISSUE THREAD

**Issue by anarquia17** [AcademiaTemple/website#29]
Se invite a que comenten sobre trabajar con bootstrap para que la pagina web de la academia sea responsive y también puedan acceder a ver desde sus moviles,  

Evidencia con el objetivo de mejorar para que la pagina sea responsive:

![Page principal 01 ](https://user-images.githubusercontent.com/35509562/96655963-7180de80-1304-11eb-8b1a-1b4d74e1fd25.jpg)
![Page principal 02 ](https://user-images.githubusercontent.com/35509562/96655965-72197500-1304-11eb-9bee-60821e901595.jpg)

**Comment by anarquia17** [comment]
Sabemos que algunos de colaboradores ya estuvieron trabajando sus issues con bootstrap y los demás que no lo trabajaron de esa forma, puedan opinar.

**Comment by Gricardov** [comment]
Estoy de acuerdo. Aunque pensaba usar media-queries cuando el diseñador nos mande la versión responsive. Sin embargo, puedes ir avanzando las partes que no variarán mucho (como la sección llamada panorama y la barra de navegación)

**Comment by israteneda** [comment]
Claro, mientras tanto creo que podríamos trabajar con Bootstrap y Css normal en el mismo proyecto dependiendo de los estilos que cada desarrollador quiera implementar.

**Comment by Grover101** [comment]
estaria bien trabajar con ambos, bootstrap y CSS, cual dominen mas

**Comment by israteneda** [comment]
Entonces por el momento trabajamos tanto con CSS o Bootstrap de acuerdo a lo que dominemos más, pero con el condicional que los componentes que realicemos sean responsivos.
