### ISSUE TITLE
Mejora en barra de navegación en el  Index, Courses y Docente

### ISSUE THREAD

**Issue by anarquia17** [AcademiaTemple/website#30]
Es necesario realizar una mejora en la barra de navegación ya que se muestra transparente y se traspone a los demás objetos.

Para ver el diseño completo se pueden dirigir al prototipo en [Figma](https://www.figma.com/file/KnjnTglY03uWmKg3gFhQMM/Academia_Temple?node-id=0%3A1)

Si tienes dudas, o sugerencias se pueden comunicar en el canal de [Discord](https://discord.gg/34M35T7)

Evidencia para mejorar:

![Page Cursos](https://user-images.githubusercontent.com/35509562/96664563-b44cb180-1318-11eb-8056-f2eef2550646.jpg)
![Page Docentes](https://user-images.githubusercontent.com/35509562/96664566-b57dde80-1318-11eb-92de-e834594ade82.jpg)

**Comment by edavot** [comment]
Comienzo con las mejoras para este issue

**Comment by israteneda** [comment]
genial

**Comment by Gricardov** [comment]
Sí chamo, sería conveniente agregarle un padding top a esa barra

**Comment by Gricardov** [comment]
Barra arreglada. Todas las demás páginas deben incluir el padding hacia arriba
