### ISSUE TITLE
Crear la página de cursos

### ISSUE THREAD

**Issue by israteneda** [AcademiaTemple/website#39]
![image](https://user-images.githubusercontent.com/20668624/97734727-906f3580-1aa7-11eb-9ac8-5f45480fe9a6.png)

La página podría lucir como este ejemplo: https://gatsby-theme-courses-demo.netlify.app/

Para realizar la tarea se puede basar en el código de este repositorio: https://github.com/daniel-seoane/gatsby-theme-courses
Es decir se podría migrar los componentes para la sección de cursos

**Comment by edavot** [comment]
Comienzo con este issue

**Comment by israteneda** [comment]
Genial
