### ISSUE TITLE
Crear CONTRIBUTING.md en la raíz del proyecto

### ISSUE THREAD

**Issue by israteneda** [AcademiaTemple/website#4]
Una guía de como contribuir en el repositorio, los pasos necesarios para crear las contribuciones [Aquí un ejemplo](https://github.com/javascriptecuador/web/blob/master/CONTRIBUTING.md)

**Comment by f0xpl0it** [comment]
Esta libre o alguien ya lo realizó?

**Comment by israteneda** [comment]
Este esta libre
