### ISSUE TITLE
Crear página detalle curso 

### ISSUE THREAD

**Issue by israteneda** [AcademiaTemple/website#40]
![image](https://user-images.githubusercontent.com/20668624/97734968-c9a7a580-1aa7-11eb-99b3-04e9426a18ed.png)

La página podría lucir como este ejemplo: https://gatsby-theme-courses-demo.netlify.app/become-react-developer/

Para realizar la tarea se puede basar en el código de este repositorio: https://github.com/daniel-seoane/gatsby-theme-courses
Es decir se podría migrar los componentes para la sección de detalle del curso

**Comment by Israel2709** [comment]
Yo adopto este Issue lml_

**Comment by Gricardov** [comment]
Se culminó este issue?

**Comment by israteneda** [comment]
Añadido por @Gricardov en #68
