### ISSUE TITLE
Crear página de los videos del curso

### ISSUE THREAD

**Issue by israteneda** [AcademiaTemple/website#41]
![image](https://user-images.githubusercontent.com/20668624/97735187-ffe52500-1aa7-11eb-894d-5496a93b552c.png)

La página podría lucir como este ejemplo: https://gatsby-theme-courses-demo.netlify.app/become-react-developer/hello-world/

Para realizar la tarea se puede basar en el código de este repositorio: https://github.com/daniel-seoane/gatsby-theme-courses
Es decir se podría migrar los componentes para la sección de los videos del curso

**Comment by zenkut** [comment]
Este

**Comment by israteneda** [comment]
Solucionado por el chamo en #68
