### ISSUE TITLE
Crear el menú de navegación del sitio

### ISSUE THREAD

**Issue by israteneda** [AcademiaTemple/website#5]
![image](https://user-images.githubusercontent.com/20668624/96076520-2170ca80-0e73-11eb-9cf6-8bbae4c12420.png)

Crear el menú del sitio, con los distintos items que se muestran en la imagen.

Para ver el diseño completo se pueden dirigir [al prototipo en Figma](https://www.figma.com/file/KnjnTglY03uWmKg3gFhQMM/Academia_Temple?node-id=0%3A1)

Si tienes dudas, o sugerencias se pueden comunicar en el canal de [Discord](https://discord.gg/34M35T7)

**Comment by edavot** [comment]
Comienzo a trabajar con esto
