### ISSUE TITLE
Crear sección imagen de fondo de la página principal

### ISSUE THREAD

**Issue by israteneda** [AcademiaTemple/website#6]
![image](https://user-images.githubusercontent.com/20668624/96076827-e58a3500-0e73-11eb-9245-d236bb8a2e6e.png)

Crear la sección que se muestra en la imagen

Para ver el diseño completo se pueden dirigir [al prototipo en Figma](https://www.figma.com/file/KnjnTglY03uWmKg3gFhQMM/Academia_Temple?node-id=0%3A1)

Si tienes dudas, o sugerencias se pueden comunicar en el canal de [Discord](https://discord.gg/34M35T7)

**Comment by f0xpl0it** [comment]
trabajaré en esta issue

**Comment by israteneda** [comment]
Ok

**Comment by Babel78** [comment]
Hola puedo hacer pr a esta issue , ya lo tengo hecho solo que no comente para que puedas asignarme T_T

**Comment by israteneda** [comment]
Ok si ya lo tienes puedes enviarlo

**Comment by israteneda** [comment]
@Maiki95 podrías tomar otro issue por favor

**Comment by f0xpl0it** [comment]
@israteneda ok ya revisaré otro issue
