### ISSUE TITLE
Sección estadísticas de la página principal

### ISSUE THREAD

**Issue by israteneda** [AcademiaTemple/website#7]
![image](https://user-images.githubusercontent.com/20668624/96077069-76611080-0e74-11eb-9814-c875e1bc207c.png)

Crear la sección que se muestra en la imagen

Para ver el diseño completo se pueden dirigir [al prototipo en Figma](https://www.figma.com/file/KnjnTglY03uWmKg3gFhQMM/Academia_Temple?node-id=0%3A1)

Si tienes dudas, o sugerencias se pueden comunicar en el canal de [Discord](https://discord.gg/34M35T7)

**Comment by GerardoQ-prog** [comment]
Profesor yo hare esta Issues

**Comment by GerardoQ-prog** [comment]
asignemela por favor :) @israteneda

**Comment by israteneda** [comment]
Ok asignado

**Comment by Gricardov** [comment]
Terminado
