### ISSUE TITLE
Sección nuestros cursos de la página principal

### ISSUE THREAD

**Issue by israteneda** [AcademiaTemple/website#8]
![image](https://user-images.githubusercontent.com/20668624/96077181-c2ac5080-0e74-11eb-8ab0-c5456b30f16a.png)

Crear la sección que se muestra en la imagen

Para ver el diseño completo se pueden dirigir [al prototipo en Figma](https://www.figma.com/file/KnjnTglY03uWmKg3gFhQMM/Academia_Temple?node-id=0%3A1)

Si tienes dudas, o sugerencias se pueden comunicar en el canal de [Discord](https://discord.gg/34M35T7)

**Comment by williams23cc** [comment]
Hola, estaré trabajando en este issue.

**Comment by Gricardov** [comment]
Hola chamo, cómo vas en esta issue?

**Comment by Gricardov** [comment]
Terminado
